### ISSUE TITLE
v2.0 (JSON API support) roadmap

### ISSUE THREAD

**Issue by jerel** [django-json-api/django-rest-framework-json-api#40]
This is a meta issue to track the tasks that need to be completed before we ship a stable version.

* [x] format simple serializers as `{ data: { type, id, attributes }` for GET and POST
* [x] change the root key from `data` to `error` if HTTP status is >= 300
* [x] format exceptions (validation errors, etc) to match the spec. #44 
* [x] write beginner friendly documentation for Read The Docs. #28
* [x] automate testing against each Python version >= 2.7 and DRF >= 2.4 #67
* [x] add an example `blog` app with fixtures that can be used for tests and as an example #42 
* [x] add tests for more complex serializer scenarios (relationships, included)

If you are working on an item create an issue for it and ask to be assigned. I will update the list item with a link to it. 

For general questions or help visit [![Gitter](https://badges.gitter.im/gitterHQ/gitter.svg)](https://gitter.im/django-json-api/django-rest-framework-json-api)

**Comment by jsenecal** [comment]
Added reference to /67

**Comment by jsenecal** [comment]
Added reference to #67
